version: "3"
services:

  #databases
  ## MariaDB
  ldb_database:
    image: linuxserver/mariadb:latest
    container_name: ldb_database
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    networks:
      - ldbbackend
    volumes:
      - /mnt/ldbdatabase:/config
  ## Redis
  ldb_redis:
    image: redis:alpine
    container_name: ldb_redis
    restart: always
    networks:
      - ldbbackend

  #apps, will build to order
  ## Barcode processor
  ldb_processor_bc:
    container_name: ldb_processor_bc
    build:
      context: barcodeprocessor/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    user: "1002:1002"
    environment:
      - REDIS_IP=ldb_redis
      - MYSQL_IP=ldb_Database
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /home/bibwsstaff/ldbinvoice:/var/ldbinvoice
    restart: always
    depends_on:
      - ldb_redis
      - ldb_database
    networks:
      - ldbbackend
  ## Order Submission Processor
  ldb_processor_os:
    container_name: ldb_processor_os
    build:
      context: ordersubmission/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    user: "1002:1002"
    environment:
      - REDIS_IP=ldb_redis
      - MYSQL_IP=ldb_Database
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /home/bibwsstaff/ldbinvoice:/var/ldbinvoice
    restart: always
    depends_on:
      - ldb_redis
      - ldb_database
    networks:
      - ldbbackend
  ## ARInvoice Processor
  ldb_processor_ar:
    container_name: ldb_processor_ar
    build:
      context: arinvoice/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    user: "1002:1002"
    environment:
      - REDIS_IP=ldb_redis
      - MYSQL_IP=ldb_Database
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /home/bibwsstaff/ldbinvoice:/var/ldbinvoice
    restart: always
    depends_on:
      - ldb_redis
      - ldb_database
    networks:
      - ldbbackend
  ## IMAP downloader
  ldb_emailwatcher:
    container_name: ldb_emailwatcher
    build:
      context: emailwatcher/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    user: "1002:1002"
    environment:
      - IMAP_ADDR=${IMAP_ADDR}
      - IMAP_USER=${IMAP_USER}
      - IMAP_PASS=${IMAP_PASS}
      - IMAP_PORT=${IMAP_PORT}
    volumes:
      - /home/bibwsstaff/ldbinvoice:/var/ldbinvoice
    restart: always
    depends_on:
      - ldb_processor_ar
      - ldb_processor_os

  # Support containers
  ## Database Updater
  ldb_dbupdater:
    container_name: ldb_dbupdater
    build:
      context: dbupdater/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    user: "1002:1002"
    environment:
    volumes:
      - /home/bibwsstaff/ldbinvoice:/var/ldbinvoice
    restart: always
    networks:
      - ldbbackend
    depends_on:
      - ldb_database
  ## Network Label Maker API
  ldb_labelprinter:
    container_name: ldb_labelprinter
    build:
      context: labelmaker/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    environment:
      - PRINTER_IP=${PRINTER_IP}
    restart: always
    networks:
      - ldbbackend
networks:
  ldbbackend:
