version: "3"
services:

  #database

  LDBdatabase:
    image: linuxserver/mariadb:latest
    container_name: LDBdatabase
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    networks:
      - ldbbackend

  ldbredis:
    image: redis:alpine
    container_name: ldbredis
    restart: always
    networks:
      - ldbbackend

  #apps, will build to order

  ldb_processor_bc:
    container_name: LDBprocessor_bc
    build:
      context: barcodeprocessor/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    user: "1002:1002"
    environment:
      - REDIS_IP=ldbredis
      - MYSQL_IP=replacesqlip
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /home/bibwsstaff/ldbinvoice:/var/ldbinvoice
    restart: always
    depends_on:
      - ldbredis
      - LDBdatabase
    networks:
      - ldbbackend
  ldb_processor_os:
    container_name: LDBprocessor_os
    build:
      context: ordersubmission/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    user: "1002:1002"
    environment:
      - REDIS_IP=ldbredis
      - MYSQL_IP=replacesqlip
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /home/bibwsstaff/ldbinvoice:/var/ldbinvoice
      - /home/bibwsstaff/googledrive/OrderSubmission:/var/import
    restart: always
    depends_on:
      - ldbredis
      - LDBdatabase
    networks:
      - ldbbackend
  ldb_processor_ar:
    container_name: LDBprocessor_ar
    build:
      context: arinvoice/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    user: "1002:1002"
    environment:
      - REDIS_IP=ldbredis
      - MYSQL_IP=replacesqlip
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /home/bibwsstaff/ldbinvoice:/var/ldbinvoice
    restart: always
    depends_on:
      - ldbredis
      - LDBdatabase
    networks:
      - ldbbackend
  emailwatcher:
    container_name: LDB_emailwatcher
    build:
      context: emailwatcher/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    user: "1002:1002"
    environment:
      - IMAP_ADDR=${IMAP_ADDR}
      - IMAP_USER=${IMAP_USER}
      - IMAP_PASS=${IMAP_PASS}
      - IMAP_PORT=${IMAP_PORT}
    volumes:
      - /home/bibwsstaff/ldbinvoice:/var/ldbinvoice
    restart: always
networks:
  ldbbackend:
